/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.testHandsOn;

import com.example.testHandsOn.controller.Rotinas;
import java.math.BigDecimal;

public class App {
    

    public static void main(String[] args) {
        
        Rotinas rot = new Rotinas();
        rot.imprimirFuncionarios();
        //rot.rmFuncionario("Maria");
        //rot.formatNum(new BigDecimal("2009.44"));
        
    }
    
    
    
}
